"""remove user_uuid

Revision ID: 689fb138eab9
Revises: 91b5eabb7b7b
Create Date: 2025-12-02 15:05:33.352998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '689fb138eab9'
down_revision: Union[str, Sequence[str], None] = '91b5eabb7b7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file_object', 'user_uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_object', sa.Column('user_uuid', sa.VARCHAR(length=36), nullable=False))
    # ### end Alembic commands ###
