"""init

Revision ID: 91b5eabb7b7b
Revises: 
Create Date: 2025-11-26 19:19:01.005951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91b5eabb7b7b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('bucket', sa.String(length=255), nullable=False),
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'PRIVATE', name='file_visibility'), nullable=False),
    sa.Column('kind', sa.Enum('IMAGE', 'PDF', 'DOCUMENT', 'OTHER', name='file_kind'), nullable=False),
    sa.Column('status', sa.Enum('PENDING_UPLOAD', 'AVAILABLE', 'FAILED', name='file_status'), nullable=False),
    sa.Column('folder', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index(op.f('ix_file_object_id'), 'file_object', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_object_id'), table_name='file_object')
    op.drop_table('file_object')
    # ### end Alembic commands ###
